//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFG_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class actuator
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public actuator()
        {
            this.actuator_value = new HashSet<actuator_value>();
        }
    
        public int id_actuator { get; set; }
        public string type { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public int id_device_associated { get; set; }
    
        public virtual device device { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<actuator_value> actuator_value { get; set; }
    }
}
