//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFG_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class plant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public plant()
        {
            this.device = new HashSet<device>();
        }
    
        public int id_plant { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public double air_temperature { get; set; }
        public double air_humidity { get; set; }
        public double ground_humidity { get; set; }
        public Nullable<double> quantity_fertilizer_week { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<device> device { get; set; }
    }
}
