//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFG_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class actuator_value
    {
        public int id_actuator_value { get; set; }
        public int execution { get; set; }
        public System.DateTime timestamp { get; set; }
        public int id_actuator_associated { get; set; }
    
        public virtual actuator actuator { get; set; }
    }
}
